all: crossproduct.pdf \
	quaternions.pdf \
	multivariatebasics.pdf

crossproduct.pdf: crossproduct.tex
	pdflatex crossproduct.tex
	pdflatex crossproduct.tex

quaternions.pdf: quaternions.tex
	pdflatex quaternions.tex
	pdflatex quaternions.tex

multivariatebasics.pdf: multivariatebasics.tex
	pdflatex multivariatebasics.tex
	pdflatex multivariatebasics.tex
