all: crossproduct.pdf \
	quaternions.pdf

crossproduct.pdf: crossproduct.tex
	pdflatex crossproduct.tex
	pdflatex crossproduct.tex

quaternions.pdf: quaternions.tex
	pdflatex quaternions.tex
	pdflatex quaternions.tex
